report_structure:
  - section: "title"
    prompt: "生成报告标题，格式为‘关于当前汛情情况的通报’，包含发布单位‘淮安市防汛防旱指挥部’和当前日期（格式：YYYY年MM月DD日）。查询关键词：{query}"
    format: "# {content}\n淮安市防汛防旱指挥部\n（{date}）\n\n入梅以来，我市及淮沂沭泗地区出现连续强降雨过程，淮河流域、沂沭泗地区相继出现洪水过程，我市大部分县（区）地区出现内涝。呈现出外洪内涝夹击的严峻态势。\n"
  - section: "rainfall"
    prompt: "根据以下内容，提取并描述雨情信息，包括降雨的时间、地点、降雨量（具体数值和单位，如毫米）、降雨过程的频率或持续时间等，内容应不少于150字。如果信息不足，补充‘暂无详细雨情数据’。上下文：\n{context}"
    format: "## 一、雨情\n{content}\n"
  - section: "water_condition"
    prompt: "根据以下内容，提取并描述水情信息，包括水位变化（时间、地点、水位值、是否超警）、流量数据（如立方米/秒）、河湖情况（如上涨速度、行洪状态），内容应不少于200字。如果信息不足，补充‘暂无详细水情数据’。上下文：\n{context}"
    format: "## 二、水情\n{content}\n"
  - section: "disaster_impact"
    prompt: "根据以下内容，提取并描述灾情信息，包括受灾时间、地点、受涝面积（如万亩）、受灾人口（如万人）、经济损失（如亿元）等，内容应不少于150字。如果信息不足，补充‘暂无详细灾情数据’。上下文：\n{context}"
    format: "## 三、灾情\n{content}\n"
  - section: "measures"
    prompt: "根据以下内容，提取并描述采取的主要措施，分为以下子项：1. 科学调度流域洪水；2. 及时抢排区域涝水；3. 严格控制水库水位；4. 及时调拨物资支持；5. 加强堤防巡查防守。每项措施需包括时间、地点、具体行动（如泄洪流量、抽水量、人员数量），若无对应信息则写‘暂无相关措施’。内容应不少于300字。上下文：\n{context}"
    format: "## 四、采取的主要措施\n针对当前防汛排涝的形势，市防指高度重视，科学调度，重点做好以下几项工作：\n{content}\n"
  - section: "future_trends"
    prompt: "根据以下内容，分析汛情趋势并提出下一步打算，包括未来降雨预测、水位变化趋势、具体应对措施（如调度、预测、巡查），分为以下子项：1. 加强水利工程调度；2. 加强预测预报；3. 加强巡堤查险；4. 争取上级支持。每项需具体描述，若无信息则写‘暂无趋势分析或计划’。内容应不少于200字。上下文：\n{context}"
    format: "## 五、趋势分析及下一步打算\n{content}\n"